In [1]:
import numpy as np

In [2]:
A=np.array([[11,12,13,14],[15,16,17,18]])

In [3]:
# least squares y ~= ax+b
# input data
x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])

In [4]:
# concatnate a constant term
A = np.vstack([x, np.ones(len(x))]).T
A

array([[0., 1.],
       [1., 1.],
       [2., 1.],
       [3., 1.]])

In [5]:
# create a matrix A'*A
At_A = A.T.dot(A)
At_A

array([[14.,  6.],
       [ 6.,  4.]])

In [6]:
# create a vector A'*b
At_y = A.T.dot(y)
At_y

array([8.3, 2.2])

In [7]:
# solve for x
from numpy.linalg import solve
c = solve(At_A, At_y)
c

array([ 1.  , -0.95])

In [8]:
# fitted value
y_fitted = A.dot(c)
y_fitted

array([-0.95,  0.05,  1.05,  2.05])

In [9]:
import matplotlib.pyplot as plt
plt.plot(x, y, 'o', label='Original data', markersize=10)
plt.plot(x, y_fitted, 'r', label='Fitted line')
plt.legend()
plt.show()

<Figure size 640x480 with 1 Axes>

In [10]:
# compute error vector
error = y-y_fitted
error

array([-0.05,  0.15, -0.15,  0.05])

In [11]:
# calculate error
np.sqrt(np.sum(error**2))

0.22360679774997896

In [12]:
# calculate error using 'norm' function
from numpy.linalg import norm
norm(y-y_fitted)

0.22360679774997896

In [13]:
# example in the slide
A=np.array([[60, 5.5, 1],[65, 4.8, 0],[55, 6.0, 1],[50, 5.0, 1]])
b=np.array([66, 70, 78, 72])

In [14]:
# create a matrix A'*A
At_A = A.T.dot(A)
At_A

array([[1.3350e+04, 1.2220e+03, 1.6500e+02],
       [1.2220e+03, 1.1429e+02, 1.6500e+01],
       [1.6500e+02, 1.6500e+01, 3.0000e+00]])

In [22]:
# create a vector A'*b
At_b = A.T.dot(b)
At_b

array([16400.,  1527.,   216.])

In [23]:
from numpy.linalg import solve
x = solve(At_A,At_b)
x

array([-0.12459016, 16.06557377, -9.50819672])

In [24]:
# fitted value
b_fitted = A.dot(x)
b_fitted

array([71.37704918, 69.01639344, 80.03278689, 64.59016393])

In [25]:
# compute error vector
error = b-b_fitted
error

array([-5.37704918,  0.98360656, -2.03278689,  7.40983607])

In [19]:
# calculate error
np.sqrt(np.sum(error**2))

9.429635877746556

In [21]:
# calculate error using 'norm' function
from numpy.linalg import norm
norm(b-b_fitted)


9.429635877746556